name: Tests

on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: tests-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  tests:
    name: Test with PHP ${{ matrix.php-version }}, VarDumper ${{ matrix.var-dumper }}, Satbility ${{ matrix.stability }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        var-dumper:
          - "4.4"
          - "5.0"
          - "6.0"
        stability:
          - "stable"
          - "lowest"

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Install PHP"
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        php-version: ${{ matrix.php-version }}
        ini-values: error_reporting=E_ALL
        tools: composer:v2

    - name: Declare required symfony/var-dumper version
      run: |
        composer require --no-update symfony/var-dumper ^${{ matrix.var-dumper }}

    - name: Install dependencies
      run: composer update --no-progress --no-suggest --prefer-${{ matrix.stability }}

    - name: Run tests
      run: ./vendor/bin/phpunit --no-coverage
